name: Build Windows MSI

on: [push]


jobs:
  build_msi:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: >-
          git
          base-devel
          gcc
          bc
        pacboy: >-
          msitools:x
          meson:x
          vala:x
          libgsf:x
          gcab:x
          gcc:x
          gobject-introspection:x
          python3:p

    - uses: actions/checkout@v3
    - name: '🚧 Build package'
      run: |
        ./packaging/windows/build_msi.sh

    - uses: actions/upload-artifact@v3
      with:
        path: syncthing-gtk.msi
